# Generated by Django 5.1.6 on 2025-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_object_type_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='sync_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
