# Generated by Django 5.1.5 on 2025-02-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0122_charfield_null_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedchange',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stagedchange',
            name='object_type',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='StagedChange',
        ),
    ]
