# Generated by Django 5.2b1 on 2025-03-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0123_remove_staging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('weight', 'name')},
        ),
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
